//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnnualTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnnualTable()
        {
            this.SessionProgramSubjectSettingTables = new HashSet<SessionProgramSubjectSettingTable>();
        }
    
        public int AnnualID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public string Title { get; set; }
        public Nullable<double> Fees { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Description { get; set; }
    
        public virtual ProgramTable ProgramTable { get; set; }
        public virtual UserTable UserTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionProgramSubjectSettingTable> SessionProgramSubjectSettingTables { get; set; }
    }
}
