//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDBAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AnnualTable
    {
        [Key]
        [Display(Name = "Annual ID")]
        public int AnnualID { get; set; }
        [Display(Name = "User ID")]
        public Nullable<int> UserID { get; set; }
        [Display(Name = "Program ID")]
        public Nullable<int> ProgramID { get; set; }

        public string Title { get; set; }
        [DataType(DataType.Currency)]
        public Nullable<double> Fees { get; set; }
        [Display(Name = "Status")]
        public Nullable<bool> IsActive { get; set; }
        public string Description { get; set; }

        public virtual ProgramTable ProgramTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
