//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDBAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ClassSubjectTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClassSubjectTable()
        {
            this.MarksTables = new HashSet<MarksTable>();
            this.TimeTableTables = new HashSet<TimeTableTable>();
        }

        [Key]
        [Display(Name = " Clas Subject ID")]
        public int ClassSubjectID { get; set; }
        [Display(Name = "Class ID")]
        public Nullable<int> ClassID { get; set; }
        [Display(Name = "Subject ID")]
        public Nullable<int> SubjectID { get; set; }
        [Display(Name = "Class Subject")]
        public string Name { get; set; }
        [Display(Name = "Status")]
        public Nullable<bool> IsActive { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarksTable> MarksTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeTableTable> TimeTableTables { get; set; }
        public virtual ClassTable ClassTable { get; set; }
        public virtual SubjectTable SubjectTable { get; set; }
    }
}
