//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDBAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EventTable
    {
        [Key]
        [Display(Name = "Event ID")]
        public int EventID { get; set; }
        [Display(Name = "Event")]
        public string EventTitle { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Event Date")]
        public Nullable<System.DateTime> EventDate { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
        [Display(Name = "User ID")]
        public Nullable<int> UserID { get; set; }

        public virtual UserTable UserTable { get; set; }
    }
}
