//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDBAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EventsTable
    {
        public int EventID { get; set; }
        public string EventTitle { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> EventDate { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual UserTable UserTable { get; set; }
    }
}
