//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamSettingTable
    {
        public int ExamSettingID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public Nullable<int> ExamID { get; set; }
        public Nullable<int> ProgramSessionID { get; set; }
        public string Description { get; set; }
    
        public virtual ExamTable ExamTable { get; set; }
        public virtual ProgramSession ProgramSession { get; set; }
        public virtual SessionTable SessionTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
