//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffAttendanceTable
    {
        public int StaffAttendanceID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<System.DateTime> AttendDate { get; set; }
        public Nullable<System.TimeSpan> Arrival { get; set; }
        public Nullable<System.TimeSpan> LeavingTime { get; set; }
    
        public virtual StaffTable StaffTable { get; set; }
    }
}
