//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDBAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class StaffTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StaffTable()
        {
            this.EmployeeSalaryTables = new HashSet<EmployeeSalaryTable>();
            this.StaffAttendanceTables = new HashSet<StaffAttendanceTable>();
            this.TimeTableTables = new HashSet<TimeTableTable>();
        }
    
        public int StaffID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Name { get; set; }
        public Nullable<int> DesignationID { get; set; }
        public string ContactNo { get; set; }
        [DataType(DataType.Currency)]
        public Nullable<double> BasicSalary { get; set; }
        public string EmailAddress { get; set; }
        public string Address { get; set; }
        public string Qualification { get; set; }
        public string Photo { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Gender { get; set; }
        public string HomePhoneNo { get; set; }
        public Nullable<bool> Doyouhaveadisability { get; set; }
        public string DisabilityDetails { get; set; }
        public Nullable<bool> Areyoutakinganymedication { get; set; }
        public string MedicationDetails { get; set; }
        public Nullable<bool> Doyouhaveacriminalrecord { get; set; }
        public string CriminalRecordDetails { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> RegistrationDate { get; set; }
    
        public virtual DesignationTable DesignationTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeSalaryTable> EmployeeSalaryTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffAttendanceTable> StaffAttendanceTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeTableTable> TimeTableTables { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
