//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDBAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class StudentAttendanceTable
    {
        public int StudentAttendanceID { get; set; }
        public int SessionID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> StudentID { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> AttendanceDate { get; set; }
        [DataType(DataType.Time)]
        public Nullable<System.TimeSpan> AttendTime { get; set; }
    
        public virtual ClassTable ClassTable { get; set; }
        public virtual SessionTable SessionTable { get; set; }
        public virtual StudentTable StudentTable { get; set; }
    }
}
