//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDBAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class StudentPromotionTable
    {
        public int StudentPromoteID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> ProgramSessionID { get; set; }
        public Nullable<int> SectionID { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> PromoteDate { get; set; }
        public Nullable<double> AnnualFree { get; set; }
        public Nullable<bool> IsPromote { get; set; }
        public Nullable<int> IsSubmitFee { get; set; }
    
        public virtual ClassTable ClassTable { get; set; }
        public virtual ProgramSession ProgramSession { get; set; }
        public virtual SectionTable SectionTable { get; set; }
        public virtual StudentTable StudentTable { get; set; }
    }
}
