//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDBAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SubmissionTable
    {
        public int SubmissionFeeID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> ProgramID { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Submission Date")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> SubmissionDate { get; set; }
        [Display(Name = "Fees Month")]
        public string FeesMonth { get; set; }
        public string Description { get; set; }
    
        public virtual ClassTable ClassTable { get; set; }
        public virtual ProgramTable ProgramTable { get; set; }
        public virtual StudentTable StudentTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
