//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTableTable
    {
        public int TimeTableID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Day { get; set; }
        public Nullable<int> ClassSubjectID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ClassSubjectTable ClassSubjectTable { get; set; }
        public virtual StaffTable StaffTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
